/**
 * Generated function schema for the frontend Rayfin client.
 *
 * Do not edit this file.
 * Rayfin function type generation replaces it when registrations change.
 */
export type AppFunctionsSchema = {
  helloWorld: {
    input: { firstName: string; lastName: string };
    output: string;
  };
};
